config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('u/', include("users.urls")),
        path('config/backup/', include("db_backup.urls")),
        path('o/', include("orders.urls")),
        path('c/', include("clients.urls")),
        path('e/', include("employee.urls")),
    ])),
    path('super/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

private/urls.py
from django.urls import path
from .views import  HomeViewPrivate, EditConfigurationView, ConfigurationView, MyProfileView, EditProfileView, CustomPasswordChangeView, MyUserActionLogView, UserActionLogView, CalendarView

app_name = 'private'

urlpatterns = [
     path('', HomeViewPrivate.as_view(), name='home'),
     path('config/', ConfigurationView.as_view(), name='view_configuration'),
     path('config/edit/', EditConfigurationView.as_view(), name='update_configuration'),
     path('config/actions/', UserActionLogView.as_view(), name = 'view_user_actions'),
     path('profile/', MyProfileView.as_view(), name='view_profile'),
     path('profile/actions/', MyUserActionLogView.as_view(), name = 'view_my_actions'),
     path('profile/edit/', EditProfileView.as_view(), name='update_profile'),
     path('profile/edit/password/', CustomPasswordChangeView.as_view(), name='update_password'),
     path('calendar/', CalendarView.as_view(), name='calendar'),
]

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

private/forms.py
from django import forms
from .models import Configuration
from users.models import User
from django.forms.widgets import ClearableFileInput
from django.contrib.auth.password_validation import validate_password

class ConfigurationForm(forms.ModelForm):
    class Meta:
        model = Configuration
        fields = ['name', 'logo', 'direction', 'phone', 'email', 'footer', 'gratitude', 'description', 'banner', 'favicon']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'logo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'direction': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'footer': forms.Textarea(attrs={'class': 'form-control'}),
            'gratitude': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 4}),
            'banner': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'favicon' : forms.ClearableFileInput(attrs={'class' : 'form-control'}),
        }
        labels = {
            'name': 'Nombre de la Organización',
            'logo': 'Logotipo',
            'direction': 'Dirección',
            'phone': 'Teléfono',
            'email': 'Correo Electrónico',
            'footer': 'Pie de página',
            'gratitud' : 'Texto de Agradecimiento',
            'description': 'Descripción Detallada',
            'banner': 'Banner',
            'favicon' : 'Icono de la pagina'
        }

class MyProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'first_name', 'last_name', 'second_last_name', 'phone_number', 'date_of_birth', 'gender', 'photo']
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'second_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone_number': forms.TextInput(attrs={'class': 'form-control'}),
            'date_of_birth': forms.DateInput(
                attrs={'class': 'form-control', 'type': 'date'},
                format='%Y-%m-%d'
                ),
            'gender': forms.Select(attrs={'class': 'form-control'}),
            'photo': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'email': 'Correo Electrónico',
            'first_name': 'Nombres',
            'last_name': 'Primer apellido',
            'second_last_name': 'Segundo Apellido',
            'phone_number': 'Número de Teléfono',
            'date_of_birth': 'Fecha de Nacimiento',
            'gender': 'Genero',
            'photo': 'Foto de Perfil',
        }


class CustomPasswordChangeForm(forms.Form):
    new_password1 = forms.CharField(
        label="Nueva contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )
    new_password2 = forms.CharField(
        label="Repetir nueva contraseña",
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
    )

    def __init__(self, *args, user=None, **kwargs):
        """
        Permite inicializar el formulario con el usuario actual.
        """
        self.user = user
        super().__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("new_password1")
        password2 = cleaned_data.get("new_password2")

        if password1 != password2:
            raise forms.ValidationError("Las contraseñas no coinciden.")

        # Validar la seguridad de la contraseña
        validate_password(password1, user=self.user)

        return cleaned_data

    def save(self, commit=True):
        """
        Guarda la nueva contraseña para el usuario.
        """
        self.user.set_password(self.cleaned_data["new_password1"])
        if commit:
            self.user.save()

private/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Configuration, UserActionLog
from .forms import ConfigurationForm, CustomPasswordChangeForm, MyProfileForm
from authentication.mixins import ValidatePermissionRequiredMixin
from django.contrib import messages
from users.models import User
from orders.models import Order
from clients.models import Client
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from datetime import date, timedelta
from django.db.models import Q
from .graphs import lastTwelveMonths, lastTwelveMonthsName
import json
from .utils import log_user_action, get_client_ip

# Create your views here.

class HomeViewPrivate(LoginRequiredMixin, TemplateView):
    template_name =  'private/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Current_date = date.today()
        Current_month = Current_date.month
        Current_year = Current_date.year

        all_orders = Order.objects.count()
        all_clients = Client.objects.count()

        orders_this_month = Order.objects.filter(Q(request_date__month=Current_month) & Q(request_date__year=Current_year)).count()
        clients_this_month = Client.objects.filter(Q(created__month=Current_month) & Q(created__year=Current_year)).count()
        
        # Quitar anulados desde aquí
        OrderNull = Order.objects.exclude(current_status__code="anulado")

        orders_this_day = OrderNull.filter(request_date=Current_date)

        # Solo pedidos no anulados con entrega hoy
        delivery_now = OrderNull.filter(deadline=Current_date)

        # Solo pedidos no anulados con entrega mañana
        delivery_tomorrow = OrderNull.filter(deadline=Current_date + timedelta(days=1))
        clients_data = lastTwelveMonths(Client, "clientes", Current_date)
        orders_data = lastTwelveMonths(Order, "orders", Current_date)
        months_name = lastTwelveMonthsName(Current_date)


        user = self.request.user
        if user.is_authenticated:
            context['user_permissions'] = user.get_all_permissions()
        else:
            context['user_permissions'] = set()  # Usuario no autenticado

        context['all_orders'] = all_orders
        context['all_clients'] = all_clients
        context['orders_this_month'] = orders_this_month
        context['clients_this_month'] = clients_this_month
        context['orders_this_day'] = orders_this_day
        context['delivery_now'] = delivery_now
        context['delivery_tomorrow'] = delivery_tomorrow
        context['clients_data'] = json.dumps(clients_data)
        context['orders_data'] = json.dumps(orders_data)
        context['months_name'] = json.dumps(months_name)
        return context
    
class ConfigurationView(LoginRequiredMixin, TemplateView):
    template_name = 'private/organization/view_organization.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            configuration = Configuration.get_configuration()
        except Configuration.DoesNotExist:
            messages.error(self.request, "La configuración no existe. Contacta al administrador.", extra_tags='error')
            configuration = None
        context['configuration'] = configuration
        return context

class EditConfigurationView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = ['private.change_configuration']
    form_class = ConfigurationForm
    template_name = 'private/organization/update_organization.html'
    success_url = 'private:view_configuration'

    def get_object(self):
        # Asegúrate de que siempre se edite la misma configuración
        return Configuration.get_configuration()
    
    def get_success_url(self):
        if not self.success_url:
            raise ValueError("No se ha configurado 'success_url'.")
        messages.success(self.request, 'Cambios realizados exitosamente.', extra_tags='success')
        return reverse(self.success_url)

    def form_valid(self, form):
        response = super().form_valid(form)  # Procesar la actualización normalmente
        
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Editó la configuración de la organización",
            model_name="Configuration",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        
        return response

class MyProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'private/profile/view_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
    
class EditProfileView(LoginRequiredMixin, UpdateView):
    form_class = MyProfileForm
    template_name = 'private/profile/update_profile.html'
    success_url = reverse_lazy('private:view_profile')

    def get_object(self, queryset=None):
        # Retorna el usuario autenticado
        return self.request.user

    def form_valid(self, form):
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Editó la información de su perfil",
            model_name="User",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        messages.success(self.request, 'Usuario actualizado exitosamente.', extra_tags='success')
        return super().form_valid(form)

class BaseUserActionLogView(LoginRequiredMixin, ListView):
    model = UserActionLog
    context_object_name = 'actions'
    ordering = '-timestamp'

class MyUserActionLogView(BaseUserActionLogView):
    template_name = 'private/actions/my_action_logs.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)[:15]

class UserActionLogView(BaseUserActionLogView):
    template_name = 'private/actions/user_action_log.html'

    def get_queryset(self):
        return super().get_queryset()[:15]
      
class CustomPasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = 'private/profile/update_password.html'
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('private:view_profile')  # Redirige tras éxito
    success_message = "¡Tu contraseña ha sido cambiada con éxito!"

    def form_valid(self, form):
        # Lógica personalizada antes de guardar la nueva contraseña
        form.save(self.request.user)  # Usa el método save del formulario personalizado
        response = super().form_valid(form)
        print("Contraseña cambiada para el usuario:", self.request.user)
        return response
    

class CalendarView(LoginRequiredMixin, TemplateView):
    template_name = 'private/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        range_filter = self.request.GET.get('range', 'recent')  # "recent" por defecto

        today = date.today()
        first_day_current = today.replace(day=1)

        if range_filter == 'recent':
            # mes anterior
            prev_month = (first_day_current - timedelta(days=1)).replace(day=1)
            # mes siguiente
            next_month = (first_day_current + timedelta(days=32)).replace(day=1)
            end_next = (next_month + timedelta(days=32)).replace(day=1) - timedelta(days=1)

            start_date = prev_month
            end_date = end_next

        else:  # 'all'
            start_date = None
            end_date = None

        orders = Order.objects.all()
        if start_date and end_date:
            orders = orders.filter(deadline__range=(start_date, end_date))

        events = [
            {
                'title': order.client.name,
                'start': order.deadline.strftime('%Y-%m-%d'),
                'end': order.deadline.strftime('%Y-%m-%d'),
                'url': reverse('orders:detail', kwargs={'pk': order.id}),
                'color': (
                    'green' if (order.current_status and order.current_status.code == "cancelado")
                    else 'gray' if (order.current_status and order.current_status.code == "anulado")
                    else 'red'
                ),
            }
            for order in orders
        ]

        context['events'] = json.dumps(events)
        context['range_filter'] = range_filter
        return context

private/templates/private/profile/update_password.html
{% extends "private/base.html" %}
{% load widget_tweaks %}
{% block content %}

<h4>Cambiar Contraseña</h4>


<form method="post">
    {% csrf_token %}
                    <div class="mb-3 position-relative">
                    {{ form.new_password1.label_tag }}
                    <div class="input-group">
                        {{ form.new_password1|add_class:"form-control" }}
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" id="togglePassword1">
                                <i class="bi bi-eye" id="togglePasswordIcon1"></i>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="mb-3 position-relative">
                    {{ form.new_password2.label_tag }}
                    <div class="input-group">
                        {{ form.new_password2|add_class:"form-control" }}
                        <div class="input-group-append">
                            <button type="button" class="btn btn-outline-secondary" id="togglePassword2">
                                <i class="bi bi-eye" id="togglePasswordIcon2"></i>
                            </button>
                        </div>
                    </div>
                </div>
    <a class="btn btn-outline-primary" href="{% url 'private:view_profile' %}">Regresar</a>
    <button class="btn btn-primary" type="submit">Cambiar contraseña</button>
</form>
{% include 'auth/show_password.html' with buttonId="togglePassword1" passwordSelector="[name='new_password1']" iconId="togglePasswordIcon1" %}
{% include 'auth/show_password.html' with buttonId="togglePassword2" passwordSelector="[name='new_password2']" iconId="togglePasswordIcon2" %}

{% endblock %}

private/templates/private/profile/update_profile.html
{% extends 'private/base.html' %}
{% load widget_tweaks %}

{% block content %}

    <div>
        <h1>Editando Mi Perfil</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        <div class="form-group">
          <label for="{{ form.photo.id_for_label }}" class="form-label">Foto</label>
          {{ form.photo|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.email.id_for_label }}" class="form-label">Correo</label>
          {{ form.email|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.first_name.id_for_label }}" class="form-label">Nombres</label>
          {{ form.first_name|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.last_name.id_for_label }}" class="form-label">Apellido</label>
          {{ form.last_name|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.phone_number.id_for_label }}" class="form-label">Teléfono</label>
          {{ form.phone_number|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.date_of_birth.id_for_label }}" class="form-label">Fecha de Nacimiento</label>
          {{ form.date_of_birth|add_class:"form-control" }}
      </div>

      <div class="form-group">
          <label for="{{ form.gender.id_for_label }}" class="form-label">Género</label>
          {{ form.gender|add_class:"form-control" }}
      </div>



        <a class="btn btn-outline-primary mt-3" href="{% url 'private:view_profile' %}">Regresar</a>
        <button class="btn btn-primary mt-3" type="submit" >Guardar</button>
      </form>
    </div>
      



{% endblock %}

private/templates/private/profile/view_profile.html
{% extends 'private/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-3">
    <div class="card position-relative">
        <!-- Imagen de portada -->
        <div class="card-header p-0">
          <div class="bg-dark" style="height: 200px; background-size: cover; background-position: center;"></div>
      </div>
<!-- Menú desplegable en la esquina superior derecha -->
<div class="dropdown position-absolute" style="top: 10px; right: 10px;">
  <button 
      class="btn btn-dark dropdown-toggle" 
      type="button" 
      id="actionMenuButton" 
      data-bs-toggle="dropdown" 
      aria-expanded="false">
      <i class="bi bi-three-dots-vertical"></i>
  </button>

  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="actionMenuButton"> 
    
    <li><a class="dropdown-item" href="{% url 'private:update_profile' %}">
      <i class="bi bi-pencil-square me-2"></i>
      Editar perfil
    </a></li>
    <li><a class="dropdown-item" href="{% url 'private:update_password' %}">
      <i class="bi bi-person-lock me-2"></i>
      Cambiar contraseña
    </a></li>

    <li><a class="dropdown-item" href="{% url 'private:view_my_actions' %}">
      <i class="bi bi-clock-history me-2"></i>
      Historial de cambios
    </a></li>

  </ul>
</div>
        {% include 'users/components/user_card.html' %}
</div>
</div>  
{% endblock content %}