config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('u/', include("users.urls")),
        path('config/backup/', include("db_backup.urls")),
        path('o/', include("orders.urls")),
        path('c/', include("clients.urls")),
        path('e/', include("employee.urls")),
    ])),
    path('super/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employee/urls.py
from django.urls import path
from .views import EmployeeListView, EmployeeDetailView, EmployeeUpdateView, EmployeeCreateView, EmployeeDeleteView
app_name = 'employee'

urlpatterns = [
    path('', EmployeeListView.as_view(), name='employee_list'),
    path('create/', EmployeeCreateView.as_view(), name='employee_create'),
    path('<int:pk>/', EmployeeDetailView.as_view(), name='employee_detail'),
    path('<int:pk>/update/', EmployeeUpdateView.as_view(), name='employee_update'),
    path('<int:pk>/delete/', EmployeeDeleteView.as_view(), name='employee_delete'),
]

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

employee/models.py
from django.db import models
from django.core.exceptions import ValidationError

def validate_eight_digits(value):
    if len(str(value)) != 8:
        raise ValidationError('El valor debe tener exactamente 8 dígitos.')


class Employee(models.Model):
    POSITION_CHOICES = [
        ('atencion', 'Atención al Cliente'),
        ('costura', 'Costura y Confección'),
        ('impresion', 'Impresión'),
        ('sublimacion', 'Sublimación'),
    ]
    UBICATION_CHOICES = (
        ('sl', 'San Luis'),
        ('ip', 'Ipala'),
    )
    name = models.CharField(max_length=60)
    created = models.DateField(auto_now_add=True)
    updated = models.DateField(auto_now=True)
    phone = models.IntegerField(
        validators=[validate_eight_digits],
        blank=True, null=True
    )
    is_working = models.BooleanField(default=True)
    position = models.CharField(max_length=20, choices=POSITION_CHOICES, default='atencion')
    ubication = models.CharField(max_length=20, choices=UBICATION_CHOICES, default='sl')
    # payment_dates = models.ManyToManyField(PaymentDate, related_name='employees_related', blank=True)

    class Meta:
        verbose_name = "Empleado"
        verbose_name_plural = "Empleados"

    def __str__(self):
        return self.name

class Payment(models.Model):
    date = models.IntegerField()
    mount = models.IntegerField(blank=True, null=True)
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)

employee/forms.py
from django import forms
from .models import Employee

class EmployeeForm(forms.ModelForm):
    class Meta:
        model = Employee
        fields = ['name',  'phone', 'ubication','is_working', 'position']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'phone': forms.TextInput(attrs={'class': 'form-control'}),
            'ubication': forms.Select(attrs={'class': 'form-control'}),
            'is_working': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
            'position': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'name': 'Nombre',
            'phone': 'Teléfono',
            'ubication': 'Ubicación',
            'is_working': 'Activo',
            'position': 'Área de trabajo',

        }

employee/views.py
from django.shortcuts import render
from .models import Employee
from django.views.generic import ListView, UpdateView, DetailView, CreateView, DeleteView
from .forms import EmployeeForm
from django.contrib import messages
from django.urls import reverse, reverse_lazy
from django.db.models import Q
# Create your views here.

class EmployeeListView(ListView):
    model = Employee
    template_name = 'employee/employee_list.html'
    context_object_name = 'employees'
    paginate_by = 10

    def apply_filters(self, queryset):
        query = self.request.GET.get("q")
        if query:
            filters = (
                Q(name__icontains=query) |
                Q(phone__icontains=query)
            )
            queryset = queryset.filter(filters)
        return queryset

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = self.apply_filters(queryset)
        # Ordenar por fecha de creación descendente
        return queryset.order_by('-created')
    
class EmployeeDetailView(DetailView):
    model = Employee
    template_name = 'employee/employee_detail.html'
    context_object_name = 'employee'
    raise_exception = False

class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = 'employee/employee_form.html'
    form_class = EmployeeForm

    def get_success_url(self):
        messages.success(self.request, "Empleado actualizado exitosamente.", extra_tags='success')
        return reverse('employee:employee_detail', kwargs={'pk': self.object.pk})

class EmployeeCreateView(CreateView):
    model = Employee
    template_name = 'employee/employee_form.html'
    form_class = EmployeeForm

    def get_success_url(self):
        messages.success(self.request, "Empleado creado exitosamente.", extra_tags='success')
        return reverse('employee:employee_detail', kwargs={'pk': self.object.pk})
    
class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'employee/employee_delete.html'
    context_object_name = 'employee'

    def get_success_url(self):
        messages.success(self.request, "Empleado eliminado exitosamente.", extra_tags='success')
        return reverse_lazy('employee:employee_list')

employee/templates/employee/employee_delete.html
{% extends 'private/base.html' %}

{% block content %}
<h1 class="mb-4 text-center">Eliminar Empleado</h1>
<form method="POST">
    {% csrf_token %}
    <div class="alert alert-danger" role="alert">
        <strong>¡Atención!</strong> ¿Estás seguro de que deseas eliminar al Empleado {{ employee.name }}?
    </div>
    
    <p class="text-muted">Esta acción no se puede deshacer.</p>
    
    <a class="btn btn-outline-secondary " href="{% url 'employee:employee_detail' employee.id %}">Cancelar</a>
    <button class="btn btn-danger " type="submit">Eliminar</button>
    
</form>

{% endblock %}

employee/templates/employee/employee_detail.html
{% extends 'private/base.html' %}
{% load static %}
{% block content %}

<h1 class="mb-4 text-center">Detalles del Colaborador</h1>
<div class="container-fluid py-4">
    <div class="card position-relative">
        <div class="card-body">
            <!-- Dropdown en la esquina superior derecha -->
            <div class="dropdown position-absolute top-0 end-0 m-3">
                <button class="btn btn-secondary dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                    <i class="bi bi-three-dots-vertical"></i> 
                </button>
                <ul class="dropdown-menu">
                    <li>
                        <a class="dropdown-item" href="{% url 'employee:employee_update' employee.id %}">
                            <i class="bi bi-pencil"></i> Editar Colaborador
                        </a>
                    </li>
                    <li>
                        <a class="dropdown-item text-danger" href="{% url 'employee:employee_delete' employee.id %}">
                            <i class="bi bi-trash"></i> Eliminar Colaborador
                        </a>
                    </li>
                </ul>
            </div>

            <!-- Contenido con imagen y datos -->
            <div class="d-flex align-items-start">
                <img src="{% static 'img/untils/nophoto.jpg' %}" width="100px" alt="userPhoto" class="me-4">
                <div>
                    <h5 class="card-title mb-2 d-inline-block">{{ employee.name }}</h5>
                    {% if employee.is_working %}
                        <span class="badge bg-success">Activo</span>
                    {% else %}
                        <span class="badge bg-danger">Retirado</span>
                    {% endif %}
                    <p class="card-text mb-0">
                         <i class="bi bi-whatsapp" ></i> {{ employee.phone }}
                    </p>
                    <p class="card-text mb-0">
                        <i class="bi bi-geo-alt"></i> {{ employee.get_ubication_display }}
                    </p>
                    <p class="card-text mb-0">
                        <i class="bi bi-briefcase"></i> {{ employee.get_position_display }}
                    </p>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

employee/templates/employee/employee_form.html
{% extends "private/base.html" %}
{% load widget_tweaks %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    <h1 class="mb-4 text-center">Formulario Empleado</h1>
    {{form.as_p}}
    {% if employee.id %}
        <a class="btn btn-outline-primary" href="{% url 'employee:employee_detail' employee.id %}">Regresar</a>
    {% else %}
    <a class="btn btn-outline-primary" href="{% url 'employee:employee_list' %}">Regresar</a>
    {% endif %}
    <button class="btn btn-primary" type="submit">Confirmar</button>
</form>
{% endblock %}

employee/templates/employee/employee_list.html
{% extends 'private/base.html' %}

{% block content %}
<h1 class="mb-4 text-center">Listado de Empleados</h1>
<div class="d-flex justify-content-between align-items-center mb-4">
    {% if request.user.role == 'admin' %}
    <a class="btn btn-primary" href="{% url 'employee:employee_create' %}">
        <i class="bi bi-person-plus"></i> Crear Colaborador
    </a>
    {% else %}
    <a class="btn btn-outline-primary disabled" href=".">
        <i class="bi bi-person-plus"></i> Crear Colaborador
    </a>
    {% endif %}
    <form method="get" class="d-flex w-50">
        <div class="input-group">
            <input 
                type="text" 
                name="q" 
                class="form-control" 
                placeholder="Buscar colaborador..." 
                value="{{ request.GET.q }}">
            <button type="submit" class="btn btn-primary">
                <i class="bi bi-search "></i>
            </button>
        </div>
    </form>
</div>
{% include 'private/frames/pagination.html' %}


<p>{{employee.name}} {{employee.get_ubication_display  }} {{employee.get_position_display  }} {{employee.is_working  }}</p>

<div class="container-fluid py-4">
    <div class="table-responsive">
        <table class="table table-striped table-hover">
            <thead class="thead-dark">
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Telefono</th>
                    <th>Ubicación</th>
                    <th>Área de Trabajo</th>
                    <th>Estado</th>
                    <th>Acción</th>
                </tr>
            </thead>
            <tbody>
                {% for employee in employees %}
                <tr>
                    <td>{{ employee.id}}</td>
                    <td>{{ employee.name }}</td>
                    <td>{{ employee.phone }}</td>
                    <td>{{employee.get_ubication_display  }} </td>
                    <td>{{employee.get_position_display}}</td>
                    <td>{{employee.is_working}}</td>
                    <td>
                        <a class="btn btn-sm btn-info" href="{% url 'employee:employee_detail' employee.id %}">
                            <i class="bi bi-eye"></i>
                        </a>
                        
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}