config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf.urls import handler404, handler403
from public.views import custom_404_view, custom_403_view

handler404 = custom_404_view
handler403 = custom_403_view

urlpatterns = [
    path('', include("public.urls")), 
    path('', include("products.urls")),
    path('auth/', include("authentication.urls")), 
    path('admin/', include([
        path('', include("private.urls")),
        path('u/', include("users.urls")),
        path('config/backup/', include("db_backup.urls")),
        path('o/', include("orders.urls")),
        path('c/', include("clients.urls")),
        path('e/', include("employee.urls")),
    ])),
    path('super/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

db_backup/urls.py
from django.urls import path
from . import views

app_name = 'backup'

urlpatterns = [
    path('', views.DatabaseBackupView.as_view(), name='db_backup'),
    path('export/', views.export_database, name='export_database'),
    path('import/', views.import_database, name='import_database'),
]

private/urls.py
from django.urls import path
from .views import  HomeViewPrivate, EditConfigurationView, ConfigurationView, MyProfileView, EditProfileView, CustomPasswordChangeView, MyUserActionLogView, UserActionLogView, CalendarView

app_name = 'private'

urlpatterns = [
     path('', HomeViewPrivate.as_view(), name='home'),
     path('config/', ConfigurationView.as_view(), name='view_configuration'),
     path('config/edit/', EditConfigurationView.as_view(), name='update_configuration'),
     path('config/actions/', UserActionLogView.as_view(), name = 'view_user_actions'),
     path('profile/', MyProfileView.as_view(), name='view_profile'),
     path('profile/actions/', MyUserActionLogView.as_view(), name = 'view_my_actions'),
     path('profile/edit/', EditProfileView.as_view(), name='update_profile'),
     path('profile/edit/password/', CustomPasswordChangeView.as_view(), name='update_password'),
     path('calendar/', CalendarView.as_view(), name='calendar'),
]

users/urls.py
from django.urls import path
from .views import UserListView, UserCreateView, UserUpdateView, UserSoftDeleteView, UserDetailView
app_name = 'users'

urlpatterns = [
    path('', UserListView.as_view(), name='list'),
    path('crear/', UserCreateView.as_view(), name='create'),
    path('<str:pk>/', UserDetailView.as_view(), name='view'),
    path('<str:pk>/editar/', UserUpdateView.as_view(), name='update'),
    path('<str:pk>/desactivar/', UserSoftDeleteView, name='desactivar'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, Permission
from .until import generate_unique_username
from PIL import Image
import secrets

def generate_random_id():
    return secrets.token_hex(32)

class User(AbstractUser):
    ROLE_CHOICES = (
        ('invited', 'Invitado'),
        ('creator', 'Creador'),
        ('admin', 'Administrador'),
    )
    GENDER_CHOICES = (
    ('male', 'Masculino'),
    ('female', 'Femenino'),
    ('prefer_not_to_say', 'Prefiero no decirlo'),
    )

    UBICATION_CHOICES = (
        ('sl', 'San Luis'),
        ('ip', 'Ipala'),
    )
    id = models.CharField(primary_key=True, max_length=64, unique=True, default=generate_random_id)
    first_name = models.CharField(max_length=255, null=True, blank=True)
    last_name = models.CharField(max_length=255, null=True, blank=True)
    second_last_name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=20, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    gender = models.CharField(max_length=20, choices=GENDER_CHOICES, null=True, blank=True)

    photo = models.ImageField(upload_to='photos', null=True, blank=True)
    role = models.CharField(max_length=10, choices=ROLE_CHOICES, default='creator')
    email = models.EmailField(unique=True, null=False, blank=False)
    username = models.CharField(max_length=255, null=True, blank=True)
    ubication = models.CharField(max_length=255, choices=UBICATION_CHOICES, default='sl', null=True, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    last_login_ip = models.GenericIPAddressField(null=True, blank=True)


    USERNAME_FIELD = 'email'  # Usa email como identificador principal
    REQUIRED_FIELDS = ['role', 'username']

    def soft_delete(self):
        self.is_active = False
        self.save()

    def save(self, *args, **kwargs):
        # Generar un username único si no existe
        if not self.username:
            self.username = generate_unique_username(self)
        
        # Llamar al método save del padre para garantizar que la imagen está disponible
        super().save(*args, **kwargs)

        # Procesar la imagen de la foto si está presente
        if self.photo:
            self._resize_image()

        # Asignar permisos específicos según el rol
        self.assign_permissions()

    def _resize_image(self):
        """
        Redimensiona la imagen a un tamaño máximo de 300x300 px si es necesario.
        """
        img_path = self.photo.path
        img = Image.open(img_path)
        max_size = (300, 300)

        if img.height > 300 or img.width > 300:
            img.thumbnail(max_size, Image.LANCZOS)  # Usar Image.LANCZOS directamente
            img.save(img_path)

    def assign_permissions(self):
        """Asigna permisos al usuario según su rol."""
        # Elimina permisos actuales para evitar duplicados
        self.user_permissions.clear()

        # Obtén los permisos según el rol
        if self.role == 'creator':
            permissions = Permission.objects.filter(codename__in=['view_user'])  # Permiso para ver usuarios
        elif self.role == 'admin':
            permissions = Permission.objects.filter(codename__in=['add_user', 'change_user', 'delete_user', 'view_user', 'change_configuration'])  # Permisos de administrador
        else:
            permissions = []

        # Asignar permisos al usuario
        self.user_permissions.add(*permissions)
    
    def get_full_name(self):
        return f'{self.first_name or ""} {self.last_name or ""} {self.second_last_name or ""}'.strip()
    
    def get_MyUser(self):
        MyUser = User.objects.get(email=self.email)
        return MyUser

    def __str__(self):
        return f'{self.get_full_name()} - {self.is_active}'

private/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import TemplateView, UpdateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Configuration, UserActionLog
from .forms import ConfigurationForm, CustomPasswordChangeForm, MyProfileForm
from authentication.mixins import ValidatePermissionRequiredMixin
from django.contrib import messages
from users.models import User
from orders.models import Order
from clients.models import Client
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin
from datetime import date, timedelta
from django.db.models import Q
from .graphs import lastTwelveMonths, lastTwelveMonthsName
import json
from .utils import log_user_action, get_client_ip

# Create your views here.

class HomeViewPrivate(LoginRequiredMixin, TemplateView):
    template_name =  'private/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        Current_date = date.today()
        Current_month = Current_date.month
        Current_year = Current_date.year

        all_orders = Order.objects.count()
        all_clients = Client.objects.count()

        orders_this_month = Order.objects.filter(Q(request_date__month=Current_month) & Q(request_date__year=Current_year)).count()
        clients_this_month = Client.objects.filter(Q(created__month=Current_month) & Q(created__year=Current_year)).count()
        
        # Quitar anulados desde aquí
        OrderNull = Order.objects.exclude(current_status__code="anulado")

        orders_this_day = OrderNull.filter(request_date=Current_date)

        # Solo pedidos no anulados con entrega hoy
        delivery_now = OrderNull.filter(deadline=Current_date)

        # Solo pedidos no anulados con entrega mañana
        delivery_tomorrow = OrderNull.filter(deadline=Current_date + timedelta(days=1))
        clients_data = lastTwelveMonths(Client, "clientes", Current_date)
        orders_data = lastTwelveMonths(Order, "orders", Current_date)
        months_name = lastTwelveMonthsName(Current_date)


        user = self.request.user
        if user.is_authenticated:
            context['user_permissions'] = user.get_all_permissions()
        else:
            context['user_permissions'] = set()  # Usuario no autenticado

        context['all_orders'] = all_orders
        context['all_clients'] = all_clients
        context['orders_this_month'] = orders_this_month
        context['clients_this_month'] = clients_this_month
        context['orders_this_day'] = orders_this_day
        context['delivery_now'] = delivery_now
        context['delivery_tomorrow'] = delivery_tomorrow
        context['clients_data'] = json.dumps(clients_data)
        context['orders_data'] = json.dumps(orders_data)
        context['months_name'] = json.dumps(months_name)
        return context
    
class ConfigurationView(LoginRequiredMixin, TemplateView):
    template_name = 'private/organization/view_organization.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            configuration = Configuration.get_configuration()
        except Configuration.DoesNotExist:
            messages.error(self.request, "La configuración no existe. Contacta al administrador.", extra_tags='error')
            configuration = None
        context['configuration'] = configuration
        return context

class EditConfigurationView(LoginRequiredMixin, ValidatePermissionRequiredMixin, UpdateView):
    permission_required = ['private.change_configuration']
    form_class = ConfigurationForm
    template_name = 'private/organization/update_organization.html'
    success_url = 'private:view_configuration'

    def get_object(self):
        # Asegúrate de que siempre se edite la misma configuración
        return Configuration.get_configuration()
    
    def get_success_url(self):
        if not self.success_url:
            raise ValueError("No se ha configurado 'success_url'.")
        messages.success(self.request, 'Cambios realizados exitosamente.', extra_tags='success')
        return reverse(self.success_url)

    def form_valid(self, form):
        response = super().form_valid(form)  # Procesar la actualización normalmente
        
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Editó la configuración de la organización",
            model_name="Configuration",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        
        return response

class MyProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'private/profile/view_profile.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['user'] = self.request.user
        return context
    
class EditProfileView(LoginRequiredMixin, UpdateView):
    form_class = MyProfileForm
    template_name = 'private/profile/update_profile.html'
    success_url = reverse_lazy('private:view_profile')

    def get_object(self, queryset=None):
        # Retorna el usuario autenticado
        return self.request.user

    def form_valid(self, form):
        # Registrar la acción del usuario
        log_user_action(
            user=self.request.user,
            action="Editó la información de su perfil",
            model_name="User",
            object_id=str(self.object.id),
            ip_address=get_client_ip(self.request),
            additional_info={"updated_fields": form.changed_data}
        )
        messages.success(self.request, 'Usuario actualizado exitosamente.', extra_tags='success')
        return super().form_valid(form)

class BaseUserActionLogView(LoginRequiredMixin, ListView):
    model = UserActionLog
    context_object_name = 'actions'
    ordering = '-timestamp'

class MyUserActionLogView(BaseUserActionLogView):
    template_name = 'private/actions/my_action_logs.html'

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)[:15]

class UserActionLogView(BaseUserActionLogView):
    template_name = 'private/actions/user_action_log.html'

    def get_queryset(self):
        return super().get_queryset()[:15]
      
class CustomPasswordChangeView(LoginRequiredMixin, SuccessMessageMixin, PasswordChangeView):
    template_name = 'private/profile/update_password.html'
    form_class = CustomPasswordChangeForm
    success_url = reverse_lazy('private:view_profile')  # Redirige tras éxito
    success_message = "¡Tu contraseña ha sido cambiada con éxito!"

    def form_valid(self, form):
        # Lógica personalizada antes de guardar la nueva contraseña
        form.save(self.request.user)  # Usa el método save del formulario personalizado
        response = super().form_valid(form)
        print("Contraseña cambiada para el usuario:", self.request.user)
        return response
    

class CalendarView(LoginRequiredMixin, TemplateView):
    template_name = 'private/calendar.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        range_filter = self.request.GET.get('range', 'recent')  # "recent" por defecto

        today = date.today()
        first_day_current = today.replace(day=1)

        if range_filter == 'recent':
            # mes anterior
            prev_month = (first_day_current - timedelta(days=1)).replace(day=1)
            # mes siguiente
            next_month = (first_day_current + timedelta(days=32)).replace(day=1)
            end_next = (next_month + timedelta(days=32)).replace(day=1) - timedelta(days=1)

            start_date = prev_month
            end_date = end_next

        else:  # 'all'
            start_date = None
            end_date = None

        orders = Order.objects.all()
        if start_date and end_date:
            orders = orders.filter(deadline__range=(start_date, end_date))

        events = [
            {
                'title': order.client.name,
                'start': order.deadline.strftime('%Y-%m-%d'),
                'end': order.deadline.strftime('%Y-%m-%d'),
                'url': reverse('orders:detail', kwargs={'pk': order.id}),
                'color': (
                    'green' if (order.current_status and order.current_status.code == "cancelado")
                    else 'gray' if (order.current_status and order.current_status.code == "anulado")
                    else 'red'
                ),
            }
            for order in orders
        ]

        context['events'] = json.dumps(events)
        context['range_filter'] = range_filter
        return context

private/templates/private/organization/update_organization.html
{% extends 'private/base.html' %}


{% block content %}

    <h1>Editar Configuración</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    
    <a  class="btn btn-outline-primary" href="{% url 'private:view_configuration' %}">Regresar</a>
    <button class="btn btn-primary" type="submit">Guardar Cambios</button>
</form>


{% endblock %}

private/templates/private/organization/view_organization.html
{% extends 'private/base.html' %}
{% load static %}

{% block content %}

    <div class="container mt-3">
        <div class="card position-relative">
            <!-- Imagen de portada -->
            <div class="card-header p-0">
              {% if organization.banner %}
              <div 
              class="bg-dark" 
              style="height: 200px; background-image: url('{{ organization.banner.url }}'); background-size: cover; background-position: center;">
          </div>
              {% else %}
              <div class="bg-dark" style="height: 200px; background-size: cover; background-position: center;"></div>
    
              {% endif %}
              
          </div>
    <!-- Menú desplegable en la esquina superior derecha -->
    {% if request.user.role == 'admin' %}
    <div class="dropdown position-absolute" style="top: 10px; right: 10px;">
      <button 
          class="btn btn-dark dropdown-toggle" 
          type="button" 
          id="actionMenuButton" 
          data-bs-toggle="dropdown" 
          aria-expanded="false">
          <i class="bi bi-three-dots-vertical"></i>
      </button>
    
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="actionMenuButton"> 
        
        <li><a class="dropdown-item" href="{% url 'private:update_configuration' %}">
          <i class="bi bi-pencil-square me-2"></i>
          Editar configuración
        </a></li>
        <li><a class="dropdown-item" href="{% url 'backup:db_backup' %}">
          <i class="bi bi-database me-2"></i>
          Copia de seguridad
        </a></li>
    
        <li><a class="dropdown-item" href="{% url 'private:view_user_actions' %}">
          <i class="bi bi-clock-history me-2"></i>
          Historial de cambios
        </a></li>
          {% if organization.phone == "30486428" %}
          <li>
      <a class="dropdown-item" href="{% url 'users:list' %}" >
        <i class="bi bi-people me-2"></i> Gestionar Usuarios
      </a>
    </li>
          {% endif %}
      </ul>
    </div>
    {% endif %}
    <div class="card-body text-center">
        <!-- Foto de perfil -->
        <div class="profile-pic-container position-relative">

            {% if organization.logo %}
          <a href="{{organization.logo.url}}" target="_blank">
          <img 
          
            class="bg-light rounded-circle border border-3 border-white position-absolute" 
            src="{{ organization.logo.url }}"
            alt="Foto de perfil" 
            style="width: 120px; height: 120px; top: -60px; left: 50%; transform: translateX(-50%);">
          </a>
        {% else %}
            <img 
              class="rounded-circle border border-3 border-white position-absolute" 
              src="{% static 'img/untils/nophoto.jpg' %}"
              alt="Foto de perfil" 
              style="width: 120px; height: 120px; top: -60px; left: 50%; transform: translateX(-50%);">
        {% endif %}
        </div>
        
        <div style="margin-top: 64px;">
            <!-- Nombre completo y rol -->
            <h3 class="text-capitalize">{{ organization.name }}</h3>
            <p class="badge bg-secondary d-none">{{ user.get_role_display }}</p>
        </div>

        <!-- Información del usuario -->
        <ul class="list-unstyled mt-1">
            <li> {{ organization.description }}</li>
        </ul>
        
    </div>
    </div>
    </div> 
    

{% endblock %}